disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Joshua Ross"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Joshua Ross"
   image = "img/author.jpg"
   imageQuality = 96
   headline = "I'm just a nerd."
   bio = "Jr DevOps Engineer"
   links = [
     { email = "mailto:contact@rossjm.dev" },
     { github = "https://github.com/JershBytes" },
     { linkedin = "https://linkedin.com/in/joshuamalcom" },
     { reddit = "https://reddit.com/user/notawesomejosh" },
     { steam = "https://steamcommunity.com/id/yaboijersh/" },
     { x-twitter = "https://x.com/JershBytes" },
  ]
